server:
  port: 8990
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://122.114.245.215:3306/general_leaf
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: general-leaf
  redis:
    host: 122.114.245.215
    port: 6379
    database: 0
    password:
debug: false
