server:
  port: 8080
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  datasource:
    username: **
    password: **
    url: jdbc:mysql://127.0.0.1:3306/general_leaf
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: general-leaf
debug: false
security:
  user:
    name: admin
    password: admin
