package com.maihb.general.modules.entity;

import java.util.ArrayList;
import java.util.List;

public class TasteFoodExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table taste_food
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table taste_food
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table taste_food
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taste_food
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public TasteFoodExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taste_food
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taste_food
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taste_food
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taste_food
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taste_food
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taste_food
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taste_food
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taste_food
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taste_food
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taste_food
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table taste_food
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFoodIdIsNull() {
            addCriterion("food_id is null");
            return (Criteria) this;
        }

        public Criteria andFoodIdIsNotNull() {
            addCriterion("food_id is not null");
            return (Criteria) this;
        }

        public Criteria andFoodIdEqualTo(Long value) {
            addCriterion("food_id =", value, "foodId");
            return (Criteria) this;
        }

        public Criteria andFoodIdNotEqualTo(Long value) {
            addCriterion("food_id <>", value, "foodId");
            return (Criteria) this;
        }

        public Criteria andFoodIdGreaterThan(Long value) {
            addCriterion("food_id >", value, "foodId");
            return (Criteria) this;
        }

        public Criteria andFoodIdGreaterThanOrEqualTo(Long value) {
            addCriterion("food_id >=", value, "foodId");
            return (Criteria) this;
        }

        public Criteria andFoodIdLessThan(Long value) {
            addCriterion("food_id <", value, "foodId");
            return (Criteria) this;
        }

        public Criteria andFoodIdLessThanOrEqualTo(Long value) {
            addCriterion("food_id <=", value, "foodId");
            return (Criteria) this;
        }

        public Criteria andFoodIdIn(List<Long> values) {
            addCriterion("food_id in", values, "foodId");
            return (Criteria) this;
        }

        public Criteria andFoodIdNotIn(List<Long> values) {
            addCriterion("food_id not in", values, "foodId");
            return (Criteria) this;
        }

        public Criteria andFoodIdBetween(Long value1, Long value2) {
            addCriterion("food_id between", value1, value2, "foodId");
            return (Criteria) this;
        }

        public Criteria andFoodIdNotBetween(Long value1, Long value2) {
            addCriterion("food_id not between", value1, value2, "foodId");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andFoodNameIsNull() {
            addCriterion("food_name is null");
            return (Criteria) this;
        }

        public Criteria andFoodNameIsNotNull() {
            addCriterion("food_name is not null");
            return (Criteria) this;
        }

        public Criteria andFoodNameEqualTo(String value) {
            addCriterion("food_name =", value, "foodName");
            return (Criteria) this;
        }

        public Criteria andFoodNameNotEqualTo(String value) {
            addCriterion("food_name <>", value, "foodName");
            return (Criteria) this;
        }

        public Criteria andFoodNameGreaterThan(String value) {
            addCriterion("food_name >", value, "foodName");
            return (Criteria) this;
        }

        public Criteria andFoodNameGreaterThanOrEqualTo(String value) {
            addCriterion("food_name >=", value, "foodName");
            return (Criteria) this;
        }

        public Criteria andFoodNameLessThan(String value) {
            addCriterion("food_name <", value, "foodName");
            return (Criteria) this;
        }

        public Criteria andFoodNameLessThanOrEqualTo(String value) {
            addCriterion("food_name <=", value, "foodName");
            return (Criteria) this;
        }

        public Criteria andFoodNameLike(String value) {
            addCriterion("food_name like", value, "foodName");
            return (Criteria) this;
        }

        public Criteria andFoodNameNotLike(String value) {
            addCriterion("food_name not like", value, "foodName");
            return (Criteria) this;
        }

        public Criteria andFoodNameIn(List<String> values) {
            addCriterion("food_name in", values, "foodName");
            return (Criteria) this;
        }

        public Criteria andFoodNameNotIn(List<String> values) {
            addCriterion("food_name not in", values, "foodName");
            return (Criteria) this;
        }

        public Criteria andFoodNameBetween(String value1, String value2) {
            addCriterion("food_name between", value1, value2, "foodName");
            return (Criteria) this;
        }

        public Criteria andFoodNameNotBetween(String value1, String value2) {
            addCriterion("food_name not between", value1, value2, "foodName");
            return (Criteria) this;
        }

        public Criteria andHasActivityIsNull() {
            addCriterion("has_activity is null");
            return (Criteria) this;
        }

        public Criteria andHasActivityIsNotNull() {
            addCriterion("has_activity is not null");
            return (Criteria) this;
        }

        public Criteria andHasActivityEqualTo(Integer value) {
            addCriterion("has_activity =", value, "hasActivity");
            return (Criteria) this;
        }

        public Criteria andHasActivityNotEqualTo(Integer value) {
            addCriterion("has_activity <>", value, "hasActivity");
            return (Criteria) this;
        }

        public Criteria andHasActivityGreaterThan(Integer value) {
            addCriterion("has_activity >", value, "hasActivity");
            return (Criteria) this;
        }

        public Criteria andHasActivityGreaterThanOrEqualTo(Integer value) {
            addCriterion("has_activity >=", value, "hasActivity");
            return (Criteria) this;
        }

        public Criteria andHasActivityLessThan(Integer value) {
            addCriterion("has_activity <", value, "hasActivity");
            return (Criteria) this;
        }

        public Criteria andHasActivityLessThanOrEqualTo(Integer value) {
            addCriterion("has_activity <=", value, "hasActivity");
            return (Criteria) this;
        }

        public Criteria andHasActivityIn(List<Integer> values) {
            addCriterion("has_activity in", values, "hasActivity");
            return (Criteria) this;
        }

        public Criteria andHasActivityNotIn(List<Integer> values) {
            addCriterion("has_activity not in", values, "hasActivity");
            return (Criteria) this;
        }

        public Criteria andHasActivityBetween(Integer value1, Integer value2) {
            addCriterion("has_activity between", value1, value2, "hasActivity");
            return (Criteria) this;
        }

        public Criteria andHasActivityNotBetween(Integer value1, Integer value2) {
            addCriterion("has_activity not between", value1, value2, "hasActivity");
            return (Criteria) this;
        }

        public Criteria andImageUrlIsNull() {
            addCriterion("image_url is null");
            return (Criteria) this;
        }

        public Criteria andImageUrlIsNotNull() {
            addCriterion("image_url is not null");
            return (Criteria) this;
        }

        public Criteria andImageUrlEqualTo(String value) {
            addCriterion("image_url =", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlNotEqualTo(String value) {
            addCriterion("image_url <>", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlGreaterThan(String value) {
            addCriterion("image_url >", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlGreaterThanOrEqualTo(String value) {
            addCriterion("image_url >=", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlLessThan(String value) {
            addCriterion("image_url <", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlLessThanOrEqualTo(String value) {
            addCriterion("image_url <=", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlLike(String value) {
            addCriterion("image_url like", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlNotLike(String value) {
            addCriterion("image_url not like", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlIn(List<String> values) {
            addCriterion("image_url in", values, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlNotIn(List<String> values) {
            addCriterion("image_url not in", values, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlBetween(String value1, String value2) {
            addCriterion("image_url between", value1, value2, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlNotBetween(String value1, String value2) {
            addCriterion("image_url not between", value1, value2, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andIsFeaturedIsNull() {
            addCriterion("is_featured is null");
            return (Criteria) this;
        }

        public Criteria andIsFeaturedIsNotNull() {
            addCriterion("is_featured is not null");
            return (Criteria) this;
        }

        public Criteria andIsFeaturedEqualTo(Integer value) {
            addCriterion("is_featured =", value, "isFeatured");
            return (Criteria) this;
        }

        public Criteria andIsFeaturedNotEqualTo(Integer value) {
            addCriterion("is_featured <>", value, "isFeatured");
            return (Criteria) this;
        }

        public Criteria andIsFeaturedGreaterThan(Integer value) {
            addCriterion("is_featured >", value, "isFeatured");
            return (Criteria) this;
        }

        public Criteria andIsFeaturedGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_featured >=", value, "isFeatured");
            return (Criteria) this;
        }

        public Criteria andIsFeaturedLessThan(Integer value) {
            addCriterion("is_featured <", value, "isFeatured");
            return (Criteria) this;
        }

        public Criteria andIsFeaturedLessThanOrEqualTo(Integer value) {
            addCriterion("is_featured <=", value, "isFeatured");
            return (Criteria) this;
        }

        public Criteria andIsFeaturedIn(List<Integer> values) {
            addCriterion("is_featured in", values, "isFeatured");
            return (Criteria) this;
        }

        public Criteria andIsFeaturedNotIn(List<Integer> values) {
            addCriterion("is_featured not in", values, "isFeatured");
            return (Criteria) this;
        }

        public Criteria andIsFeaturedBetween(Integer value1, Integer value2) {
            addCriterion("is_featured between", value1, value2, "isFeatured");
            return (Criteria) this;
        }

        public Criteria andIsFeaturedNotBetween(Integer value1, Integer value2) {
            addCriterion("is_featured not between", value1, value2, "isFeatured");
            return (Criteria) this;
        }

        public Criteria andIsGumIsNull() {
            addCriterion("is_gum is null");
            return (Criteria) this;
        }

        public Criteria andIsGumIsNotNull() {
            addCriterion("is_gum is not null");
            return (Criteria) this;
        }

        public Criteria andIsGumEqualTo(Integer value) {
            addCriterion("is_gum =", value, "isGum");
            return (Criteria) this;
        }

        public Criteria andIsGumNotEqualTo(Integer value) {
            addCriterion("is_gum <>", value, "isGum");
            return (Criteria) this;
        }

        public Criteria andIsGumGreaterThan(Integer value) {
            addCriterion("is_gum >", value, "isGum");
            return (Criteria) this;
        }

        public Criteria andIsGumGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_gum >=", value, "isGum");
            return (Criteria) this;
        }

        public Criteria andIsGumLessThan(Integer value) {
            addCriterion("is_gum <", value, "isGum");
            return (Criteria) this;
        }

        public Criteria andIsGumLessThanOrEqualTo(Integer value) {
            addCriterion("is_gum <=", value, "isGum");
            return (Criteria) this;
        }

        public Criteria andIsGumIn(List<Integer> values) {
            addCriterion("is_gum in", values, "isGum");
            return (Criteria) this;
        }

        public Criteria andIsGumNotIn(List<Integer> values) {
            addCriterion("is_gum not in", values, "isGum");
            return (Criteria) this;
        }

        public Criteria andIsGumBetween(Integer value1, Integer value2) {
            addCriterion("is_gum between", value1, value2, "isGum");
            return (Criteria) this;
        }

        public Criteria andIsGumNotBetween(Integer value1, Integer value2) {
            addCriterion("is_gum not between", value1, value2, "isGum");
            return (Criteria) this;
        }

        public Criteria andIsNewIsNull() {
            addCriterion("is_new is null");
            return (Criteria) this;
        }

        public Criteria andIsNewIsNotNull() {
            addCriterion("is_new is not null");
            return (Criteria) this;
        }

        public Criteria andIsNewEqualTo(Integer value) {
            addCriterion("is_new =", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewNotEqualTo(Integer value) {
            addCriterion("is_new <>", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewGreaterThan(Integer value) {
            addCriterion("is_new >", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_new >=", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewLessThan(Integer value) {
            addCriterion("is_new <", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewLessThanOrEqualTo(Integer value) {
            addCriterion("is_new <=", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewIn(List<Integer> values) {
            addCriterion("is_new in", values, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewNotIn(List<Integer> values) {
            addCriterion("is_new not in", values, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewBetween(Integer value1, Integer value2) {
            addCriterion("is_new between", value1, value2, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewNotBetween(Integer value1, Integer value2) {
            addCriterion("is_new not between", value1, value2, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsSpicyIsNull() {
            addCriterion("is_spicy is null");
            return (Criteria) this;
        }

        public Criteria andIsSpicyIsNotNull() {
            addCriterion("is_spicy is not null");
            return (Criteria) this;
        }

        public Criteria andIsSpicyEqualTo(Integer value) {
            addCriterion("is_spicy =", value, "isSpicy");
            return (Criteria) this;
        }

        public Criteria andIsSpicyNotEqualTo(Integer value) {
            addCriterion("is_spicy <>", value, "isSpicy");
            return (Criteria) this;
        }

        public Criteria andIsSpicyGreaterThan(Integer value) {
            addCriterion("is_spicy >", value, "isSpicy");
            return (Criteria) this;
        }

        public Criteria andIsSpicyGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_spicy >=", value, "isSpicy");
            return (Criteria) this;
        }

        public Criteria andIsSpicyLessThan(Integer value) {
            addCriterion("is_spicy <", value, "isSpicy");
            return (Criteria) this;
        }

        public Criteria andIsSpicyLessThanOrEqualTo(Integer value) {
            addCriterion("is_spicy <=", value, "isSpicy");
            return (Criteria) this;
        }

        public Criteria andIsSpicyIn(List<Integer> values) {
            addCriterion("is_spicy in", values, "isSpicy");
            return (Criteria) this;
        }

        public Criteria andIsSpicyNotIn(List<Integer> values) {
            addCriterion("is_spicy not in", values, "isSpicy");
            return (Criteria) this;
        }

        public Criteria andIsSpicyBetween(Integer value1, Integer value2) {
            addCriterion("is_spicy between", value1, value2, "isSpicy");
            return (Criteria) this;
        }

        public Criteria andIsSpicyNotBetween(Integer value1, Integer value2) {
            addCriterion("is_spicy not between", value1, value2, "isSpicy");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNull() {
            addCriterion("is_valid is null");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNotNull() {
            addCriterion("is_valid is not null");
            return (Criteria) this;
        }

        public Criteria andIsValidEqualTo(Integer value) {
            addCriterion("is_valid =", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotEqualTo(Integer value) {
            addCriterion("is_valid <>", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThan(Integer value) {
            addCriterion("is_valid >", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_valid >=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThan(Integer value) {
            addCriterion("is_valid <", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThanOrEqualTo(Integer value) {
            addCriterion("is_valid <=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidIn(List<Integer> values) {
            addCriterion("is_valid in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotIn(List<Integer> values) {
            addCriterion("is_valid not in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidBetween(Integer value1, Integer value2) {
            addCriterion("is_valid between", value1, value2, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotBetween(Integer value1, Integer value2) {
            addCriterion("is_valid not between", value1, value2, "isValid");
            return (Criteria) this;
        }

        public Criteria andNumRatingsIsNull() {
            addCriterion("num_ratings is null");
            return (Criteria) this;
        }

        public Criteria andNumRatingsIsNotNull() {
            addCriterion("num_ratings is not null");
            return (Criteria) this;
        }

        public Criteria andNumRatingsEqualTo(Integer value) {
            addCriterion("num_ratings =", value, "numRatings");
            return (Criteria) this;
        }

        public Criteria andNumRatingsNotEqualTo(Integer value) {
            addCriterion("num_ratings <>", value, "numRatings");
            return (Criteria) this;
        }

        public Criteria andNumRatingsGreaterThan(Integer value) {
            addCriterion("num_ratings >", value, "numRatings");
            return (Criteria) this;
        }

        public Criteria andNumRatingsGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_ratings >=", value, "numRatings");
            return (Criteria) this;
        }

        public Criteria andNumRatingsLessThan(Integer value) {
            addCriterion("num_ratings <", value, "numRatings");
            return (Criteria) this;
        }

        public Criteria andNumRatingsLessThanOrEqualTo(Integer value) {
            addCriterion("num_ratings <=", value, "numRatings");
            return (Criteria) this;
        }

        public Criteria andNumRatingsIn(List<Integer> values) {
            addCriterion("num_ratings in", values, "numRatings");
            return (Criteria) this;
        }

        public Criteria andNumRatingsNotIn(List<Integer> values) {
            addCriterion("num_ratings not in", values, "numRatings");
            return (Criteria) this;
        }

        public Criteria andNumRatingsBetween(Integer value1, Integer value2) {
            addCriterion("num_ratings between", value1, value2, "numRatings");
            return (Criteria) this;
        }

        public Criteria andNumRatingsNotBetween(Integer value1, Integer value2) {
            addCriterion("num_ratings not between", value1, value2, "numRatings");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Double value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Double value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Double value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Double value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Double value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Double> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Double> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Double value1, Double value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Double value1, Double value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andRecentPopularityIsNull() {
            addCriterion("recent_popularity is null");
            return (Criteria) this;
        }

        public Criteria andRecentPopularityIsNotNull() {
            addCriterion("recent_popularity is not null");
            return (Criteria) this;
        }

        public Criteria andRecentPopularityEqualTo(Integer value) {
            addCriterion("recent_popularity =", value, "recentPopularity");
            return (Criteria) this;
        }

        public Criteria andRecentPopularityNotEqualTo(Integer value) {
            addCriterion("recent_popularity <>", value, "recentPopularity");
            return (Criteria) this;
        }

        public Criteria andRecentPopularityGreaterThan(Integer value) {
            addCriterion("recent_popularity >", value, "recentPopularity");
            return (Criteria) this;
        }

        public Criteria andRecentPopularityGreaterThanOrEqualTo(Integer value) {
            addCriterion("recent_popularity >=", value, "recentPopularity");
            return (Criteria) this;
        }

        public Criteria andRecentPopularityLessThan(Integer value) {
            addCriterion("recent_popularity <", value, "recentPopularity");
            return (Criteria) this;
        }

        public Criteria andRecentPopularityLessThanOrEqualTo(Integer value) {
            addCriterion("recent_popularity <=", value, "recentPopularity");
            return (Criteria) this;
        }

        public Criteria andRecentPopularityIn(List<Integer> values) {
            addCriterion("recent_popularity in", values, "recentPopularity");
            return (Criteria) this;
        }

        public Criteria andRecentPopularityNotIn(List<Integer> values) {
            addCriterion("recent_popularity not in", values, "recentPopularity");
            return (Criteria) this;
        }

        public Criteria andRecentPopularityBetween(Integer value1, Integer value2) {
            addCriterion("recent_popularity between", value1, value2, "recentPopularity");
            return (Criteria) this;
        }

        public Criteria andRecentPopularityNotBetween(Integer value1, Integer value2) {
            addCriterion("recent_popularity not between", value1, value2, "recentPopularity");
            return (Criteria) this;
        }

        public Criteria andRecentRatingIsNull() {
            addCriterion("recent_rating is null");
            return (Criteria) this;
        }

        public Criteria andRecentRatingIsNotNull() {
            addCriterion("recent_rating is not null");
            return (Criteria) this;
        }

        public Criteria andRecentRatingEqualTo(Double value) {
            addCriterion("recent_rating =", value, "recentRating");
            return (Criteria) this;
        }

        public Criteria andRecentRatingNotEqualTo(Double value) {
            addCriterion("recent_rating <>", value, "recentRating");
            return (Criteria) this;
        }

        public Criteria andRecentRatingGreaterThan(Double value) {
            addCriterion("recent_rating >", value, "recentRating");
            return (Criteria) this;
        }

        public Criteria andRecentRatingGreaterThanOrEqualTo(Double value) {
            addCriterion("recent_rating >=", value, "recentRating");
            return (Criteria) this;
        }

        public Criteria andRecentRatingLessThan(Double value) {
            addCriterion("recent_rating <", value, "recentRating");
            return (Criteria) this;
        }

        public Criteria andRecentRatingLessThanOrEqualTo(Double value) {
            addCriterion("recent_rating <=", value, "recentRating");
            return (Criteria) this;
        }

        public Criteria andRecentRatingIn(List<Double> values) {
            addCriterion("recent_rating in", values, "recentRating");
            return (Criteria) this;
        }

        public Criteria andRecentRatingNotIn(List<Double> values) {
            addCriterion("recent_rating not in", values, "recentRating");
            return (Criteria) this;
        }

        public Criteria andRecentRatingBetween(Double value1, Double value2) {
            addCriterion("recent_rating between", value1, value2, "recentRating");
            return (Criteria) this;
        }

        public Criteria andRecentRatingNotBetween(Double value1, Double value2) {
            addCriterion("recent_rating not between", value1, value2, "recentRating");
            return (Criteria) this;
        }

        public Criteria andRestaurantIdIsNull() {
            addCriterion("restaurant_id is null");
            return (Criteria) this;
        }

        public Criteria andRestaurantIdIsNotNull() {
            addCriterion("restaurant_id is not null");
            return (Criteria) this;
        }

        public Criteria andRestaurantIdEqualTo(Long value) {
            addCriterion("restaurant_id =", value, "restaurantId");
            return (Criteria) this;
        }

        public Criteria andRestaurantIdNotEqualTo(Long value) {
            addCriterion("restaurant_id <>", value, "restaurantId");
            return (Criteria) this;
        }

        public Criteria andRestaurantIdGreaterThan(Long value) {
            addCriterion("restaurant_id >", value, "restaurantId");
            return (Criteria) this;
        }

        public Criteria andRestaurantIdGreaterThanOrEqualTo(Long value) {
            addCriterion("restaurant_id >=", value, "restaurantId");
            return (Criteria) this;
        }

        public Criteria andRestaurantIdLessThan(Long value) {
            addCriterion("restaurant_id <", value, "restaurantId");
            return (Criteria) this;
        }

        public Criteria andRestaurantIdLessThanOrEqualTo(Long value) {
            addCriterion("restaurant_id <=", value, "restaurantId");
            return (Criteria) this;
        }

        public Criteria andRestaurantIdIn(List<Long> values) {
            addCriterion("restaurant_id in", values, "restaurantId");
            return (Criteria) this;
        }

        public Criteria andRestaurantIdNotIn(List<Long> values) {
            addCriterion("restaurant_id not in", values, "restaurantId");
            return (Criteria) this;
        }

        public Criteria andRestaurantIdBetween(Long value1, Long value2) {
            addCriterion("restaurant_id between", value1, value2, "restaurantId");
            return (Criteria) this;
        }

        public Criteria andRestaurantIdNotBetween(Long value1, Long value2) {
            addCriterion("restaurant_id not between", value1, value2, "restaurantId");
            return (Criteria) this;
        }

        public Criteria andRestaurantNameIsNull() {
            addCriterion("restaurant_name is null");
            return (Criteria) this;
        }

        public Criteria andRestaurantNameIsNotNull() {
            addCriterion("restaurant_name is not null");
            return (Criteria) this;
        }

        public Criteria andRestaurantNameEqualTo(Integer value) {
            addCriterion("restaurant_name =", value, "restaurantName");
            return (Criteria) this;
        }

        public Criteria andRestaurantNameNotEqualTo(Integer value) {
            addCriterion("restaurant_name <>", value, "restaurantName");
            return (Criteria) this;
        }

        public Criteria andRestaurantNameGreaterThan(Integer value) {
            addCriterion("restaurant_name >", value, "restaurantName");
            return (Criteria) this;
        }

        public Criteria andRestaurantNameGreaterThanOrEqualTo(Integer value) {
            addCriterion("restaurant_name >=", value, "restaurantName");
            return (Criteria) this;
        }

        public Criteria andRestaurantNameLessThan(Integer value) {
            addCriterion("restaurant_name <", value, "restaurantName");
            return (Criteria) this;
        }

        public Criteria andRestaurantNameLessThanOrEqualTo(Integer value) {
            addCriterion("restaurant_name <=", value, "restaurantName");
            return (Criteria) this;
        }

        public Criteria andRestaurantNameIn(List<Integer> values) {
            addCriterion("restaurant_name in", values, "restaurantName");
            return (Criteria) this;
        }

        public Criteria andRestaurantNameNotIn(List<Integer> values) {
            addCriterion("restaurant_name not in", values, "restaurantName");
            return (Criteria) this;
        }

        public Criteria andRestaurantNameBetween(Integer value1, Integer value2) {
            addCriterion("restaurant_name between", value1, value2, "restaurantName");
            return (Criteria) this;
        }

        public Criteria andRestaurantNameNotBetween(Integer value1, Integer value2) {
            addCriterion("restaurant_name not between", value1, value2, "restaurantName");
            return (Criteria) this;
        }

        public Criteria andStockIsNull() {
            addCriterion("stock is null");
            return (Criteria) this;
        }

        public Criteria andStockIsNotNull() {
            addCriterion("stock is not null");
            return (Criteria) this;
        }

        public Criteria andStockEqualTo(Integer value) {
            addCriterion("stock =", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockNotEqualTo(Integer value) {
            addCriterion("stock <>", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockGreaterThan(Integer value) {
            addCriterion("stock >", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockGreaterThanOrEqualTo(Integer value) {
            addCriterion("stock >=", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockLessThan(Integer value) {
            addCriterion("stock <", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockLessThanOrEqualTo(Integer value) {
            addCriterion("stock <=", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockIn(List<Integer> values) {
            addCriterion("stock in", values, "stock");
            return (Criteria) this;
        }

        public Criteria andStockNotIn(List<Integer> values) {
            addCriterion("stock not in", values, "stock");
            return (Criteria) this;
        }

        public Criteria andStockBetween(Integer value1, Integer value2) {
            addCriterion("stock between", value1, value2, "stock");
            return (Criteria) this;
        }

        public Criteria andStockNotBetween(Integer value1, Integer value2) {
            addCriterion("stock not between", value1, value2, "stock");
            return (Criteria) this;
        }

        public Criteria andAttributesIsNull() {
            addCriterion("attributes is null");
            return (Criteria) this;
        }

        public Criteria andAttributesIsNotNull() {
            addCriterion("attributes is not null");
            return (Criteria) this;
        }

        public Criteria andAttributesEqualTo(String value) {
            addCriterion("attributes =", value, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesNotEqualTo(String value) {
            addCriterion("attributes <>", value, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesGreaterThan(String value) {
            addCriterion("attributes >", value, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesGreaterThanOrEqualTo(String value) {
            addCriterion("attributes >=", value, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesLessThan(String value) {
            addCriterion("attributes <", value, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesLessThanOrEqualTo(String value) {
            addCriterion("attributes <=", value, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesLike(String value) {
            addCriterion("attributes like", value, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesNotLike(String value) {
            addCriterion("attributes not like", value, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesIn(List<String> values) {
            addCriterion("attributes in", values, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesNotIn(List<String> values) {
            addCriterion("attributes not in", values, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesBetween(String value1, String value2) {
            addCriterion("attributes between", value1, value2, "attributes");
            return (Criteria) this;
        }

        public Criteria andAttributesNotBetween(String value1, String value2) {
            addCriterion("attributes not between", value1, value2, "attributes");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table taste_food
     *
     * @mbg.generated do_not_delete_during_merge Wed Mar 28 17:16:09 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table taste_food
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}