package com.maihb.general.modules.entity;

import java.util.Date;

public class TasteFoodCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taste_food_category.category_id
     *
     * @mbg.generated Wed Mar 28 17:27:40 CST 2018
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taste_food_category.category_name
     *
     * @mbg.generated Wed Mar 28 17:27:40 CST 2018
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taste_food_category.is_valid
     *
     * @mbg.generated Wed Mar 28 17:27:40 CST 2018
     */
    private Integer isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taste_food_category.weight
     *
     * @mbg.generated Wed Mar 28 17:27:40 CST 2018
     */
    private Integer weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taste_food_category.description
     *
     * @mbg.generated Wed Mar 28 17:27:40 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taste_food_category.restaurant_id
     *
     * @mbg.generated Wed Mar 28 17:27:40 CST 2018
     */
    private Long restaurantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taste_food_category.updated_at
     *
     * @mbg.generated Wed Mar 28 17:27:40 CST 2018
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taste_food_category.display_attribute
     *
     * @mbg.generated Wed Mar 28 17:27:40 CST 2018
     */
    private String displayAttribute;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taste_food_category.category_id
     *
     * @return the value of taste_food_category.category_id
     *
     * @mbg.generated Wed Mar 28 17:27:40 CST 2018
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taste_food_category.category_id
     *
     * @param categoryId the value for taste_food_category.category_id
     *
     * @mbg.generated Wed Mar 28 17:27:40 CST 2018
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taste_food_category.category_name
     *
     * @return the value of taste_food_category.category_name
     *
     * @mbg.generated Wed Mar 28 17:27:40 CST 2018
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taste_food_category.category_name
     *
     * @param categoryName the value for taste_food_category.category_name
     *
     * @mbg.generated Wed Mar 28 17:27:40 CST 2018
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taste_food_category.is_valid
     *
     * @return the value of taste_food_category.is_valid
     *
     * @mbg.generated Wed Mar 28 17:27:40 CST 2018
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taste_food_category.is_valid
     *
     * @param isValid the value for taste_food_category.is_valid
     *
     * @mbg.generated Wed Mar 28 17:27:40 CST 2018
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taste_food_category.weight
     *
     * @return the value of taste_food_category.weight
     *
     * @mbg.generated Wed Mar 28 17:27:40 CST 2018
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taste_food_category.weight
     *
     * @param weight the value for taste_food_category.weight
     *
     * @mbg.generated Wed Mar 28 17:27:40 CST 2018
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taste_food_category.description
     *
     * @return the value of taste_food_category.description
     *
     * @mbg.generated Wed Mar 28 17:27:40 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taste_food_category.description
     *
     * @param description the value for taste_food_category.description
     *
     * @mbg.generated Wed Mar 28 17:27:40 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taste_food_category.restaurant_id
     *
     * @return the value of taste_food_category.restaurant_id
     *
     * @mbg.generated Wed Mar 28 17:27:40 CST 2018
     */
    public Long getRestaurantId() {
        return restaurantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taste_food_category.restaurant_id
     *
     * @param restaurantId the value for taste_food_category.restaurant_id
     *
     * @mbg.generated Wed Mar 28 17:27:40 CST 2018
     */
    public void setRestaurantId(Long restaurantId) {
        this.restaurantId = restaurantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taste_food_category.updated_at
     *
     * @return the value of taste_food_category.updated_at
     *
     * @mbg.generated Wed Mar 28 17:27:40 CST 2018
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taste_food_category.updated_at
     *
     * @param updatedAt the value for taste_food_category.updated_at
     *
     * @mbg.generated Wed Mar 28 17:27:40 CST 2018
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taste_food_category.display_attribute
     *
     * @return the value of taste_food_category.display_attribute
     *
     * @mbg.generated Wed Mar 28 17:27:40 CST 2018
     */
    public String getDisplayAttribute() {
        return displayAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taste_food_category.display_attribute
     *
     * @param displayAttribute the value for taste_food_category.display_attribute
     *
     * @mbg.generated Wed Mar 28 17:27:40 CST 2018
     */
    public void setDisplayAttribute(String displayAttribute) {
        this.displayAttribute = displayAttribute == null ? null : displayAttribute.trim();
    }
}