package com.maihb.general.modules.entity;

public class TasteFood {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taste_food.food_id
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    private Long foodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taste_food.description
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taste_food.food_name
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    private String foodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taste_food.has_activity
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    private Integer hasActivity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taste_food.image_url
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taste_food.is_featured
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    private Integer isFeatured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taste_food.is_gum
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    private Integer isGum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taste_food.is_new
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    private Integer isNew;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taste_food.is_spicy
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    private Integer isSpicy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taste_food.is_valid
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    private Integer isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taste_food.num_ratings
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    private Integer numRatings;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taste_food.price
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taste_food.recent_popularity
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    private Integer recentPopularity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taste_food.recent_rating
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    private Double recentRating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taste_food.restaurant_id
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    private Long restaurantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taste_food.restaurant_name
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    private Integer restaurantName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taste_food.stock
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taste_food.attributes
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    private String attributes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taste_food.food_id
     *
     * @return the value of taste_food.food_id
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public Long getFoodId() {
        return foodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taste_food.food_id
     *
     * @param foodId the value for taste_food.food_id
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public void setFoodId(Long foodId) {
        this.foodId = foodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taste_food.description
     *
     * @return the value of taste_food.description
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taste_food.description
     *
     * @param description the value for taste_food.description
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taste_food.food_name
     *
     * @return the value of taste_food.food_name
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public String getFoodName() {
        return foodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taste_food.food_name
     *
     * @param foodName the value for taste_food.food_name
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public void setFoodName(String foodName) {
        this.foodName = foodName == null ? null : foodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taste_food.has_activity
     *
     * @return the value of taste_food.has_activity
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public Integer getHasActivity() {
        return hasActivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taste_food.has_activity
     *
     * @param hasActivity the value for taste_food.has_activity
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public void setHasActivity(Integer hasActivity) {
        this.hasActivity = hasActivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taste_food.image_url
     *
     * @return the value of taste_food.image_url
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taste_food.image_url
     *
     * @param imageUrl the value for taste_food.image_url
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taste_food.is_featured
     *
     * @return the value of taste_food.is_featured
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public Integer getIsFeatured() {
        return isFeatured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taste_food.is_featured
     *
     * @param isFeatured the value for taste_food.is_featured
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public void setIsFeatured(Integer isFeatured) {
        this.isFeatured = isFeatured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taste_food.is_gum
     *
     * @return the value of taste_food.is_gum
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public Integer getIsGum() {
        return isGum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taste_food.is_gum
     *
     * @param isGum the value for taste_food.is_gum
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public void setIsGum(Integer isGum) {
        this.isGum = isGum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taste_food.is_new
     *
     * @return the value of taste_food.is_new
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public Integer getIsNew() {
        return isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taste_food.is_new
     *
     * @param isNew the value for taste_food.is_new
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public void setIsNew(Integer isNew) {
        this.isNew = isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taste_food.is_spicy
     *
     * @return the value of taste_food.is_spicy
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public Integer getIsSpicy() {
        return isSpicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taste_food.is_spicy
     *
     * @param isSpicy the value for taste_food.is_spicy
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public void setIsSpicy(Integer isSpicy) {
        this.isSpicy = isSpicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taste_food.is_valid
     *
     * @return the value of taste_food.is_valid
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taste_food.is_valid
     *
     * @param isValid the value for taste_food.is_valid
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taste_food.num_ratings
     *
     * @return the value of taste_food.num_ratings
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public Integer getNumRatings() {
        return numRatings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taste_food.num_ratings
     *
     * @param numRatings the value for taste_food.num_ratings
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public void setNumRatings(Integer numRatings) {
        this.numRatings = numRatings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taste_food.price
     *
     * @return the value of taste_food.price
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taste_food.price
     *
     * @param price the value for taste_food.price
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taste_food.recent_popularity
     *
     * @return the value of taste_food.recent_popularity
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public Integer getRecentPopularity() {
        return recentPopularity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taste_food.recent_popularity
     *
     * @param recentPopularity the value for taste_food.recent_popularity
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public void setRecentPopularity(Integer recentPopularity) {
        this.recentPopularity = recentPopularity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taste_food.recent_rating
     *
     * @return the value of taste_food.recent_rating
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public Double getRecentRating() {
        return recentRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taste_food.recent_rating
     *
     * @param recentRating the value for taste_food.recent_rating
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public void setRecentRating(Double recentRating) {
        this.recentRating = recentRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taste_food.restaurant_id
     *
     * @return the value of taste_food.restaurant_id
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public Long getRestaurantId() {
        return restaurantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taste_food.restaurant_id
     *
     * @param restaurantId the value for taste_food.restaurant_id
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public void setRestaurantId(Long restaurantId) {
        this.restaurantId = restaurantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taste_food.restaurant_name
     *
     * @return the value of taste_food.restaurant_name
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public Integer getRestaurantName() {
        return restaurantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taste_food.restaurant_name
     *
     * @param restaurantName the value for taste_food.restaurant_name
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public void setRestaurantName(Integer restaurantName) {
        this.restaurantName = restaurantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taste_food.stock
     *
     * @return the value of taste_food.stock
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taste_food.stock
     *
     * @param stock the value for taste_food.stock
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taste_food.attributes
     *
     * @return the value of taste_food.attributes
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public String getAttributes() {
        return attributes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taste_food.attributes
     *
     * @param attributes the value for taste_food.attributes
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    public void setAttributes(String attributes) {
        this.attributes = attributes == null ? null : attributes.trim();
    }
}