package com.maihb.general.modules.mapper;

import com.maihb.general.modules.entity.TasteFood;
import com.maihb.general.modules.entity.TasteFoodExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TasteFoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taste_food
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    long countByExample(TasteFoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taste_food
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    int deleteByExample(TasteFoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taste_food
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    int insert(TasteFood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taste_food
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    int insertSelective(TasteFood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taste_food
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    List<TasteFood> selectByExample(TasteFoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taste_food
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") TasteFood record, @Param("example") TasteFoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taste_food
     *
     * @mbg.generated Wed Mar 28 17:16:09 CST 2018
     */
    int updateByExample(@Param("record") TasteFood record, @Param("example") TasteFoodExample example);
}